openapi: 3.0.0
info:
  version: 1.0.0
  title: Project Management Service
components:
  schemas:
    NewProject:
      type: object
      required:
        - name
        - state
        - progress
      properties:
        name:
          type: string
        state:
          type: string
          enum: [ planned, active, done, failed ]
          default: planned
        progress:
          type: number

    Project:
      allOf:
        - $ref: '#/components/schemas/NewProject'
        - type: object
          required:
            - "id"
          properties:
            id:
              type: string
            owner:
              $ref: '#/components/schemas/Employee'
            paticipants:
              type: array
              items:
                $ref: '#/components/schemas/Employee'
              description: paticipants in the project

    Employee:
      type: object
      required:
        - id
        - firstName
        - lastName
        - role
        - email
        - department
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string
        email:
          type: string
        department:
          type: string


paths:
  /projects:
    post:
      summary: Create new Project
      operationId: createProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProject'
      responses:
        '201':
          description: Project is created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        '400':
          description: Bad request
        '409':
          description: Conflict in insertion
        '500':
          description: Internal server error

    get:
      summary: Get all projects
      operationId: getProjects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Project'
        '400':
          description: Bad request
        '500':
          description: Internal server error

  '/projects/{id}':
    put:
      summary: Update project
      operationId: updateProject
      parameters:
        - name: id
          in: path
          description: ID of the project
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProject'
      responses:
        '204':
          description: Project is updated
        '400':
          description: Bad request
        '404':
          description: Not Found
        '500':
          description: Internal server error

  '/projects/{id}/assign/owner':
    post:
      summary: Assign owner to project
      operationId: assignProjectOwner
      parameters:
        - name: id
          in: path
          description: ID of the project to assign owner to
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeId:
                  type: string
      responses:
        '200':
          description: Project is updated
        '400':
          description: Bad request
        '404':
          description: Not Found
        '500':
          description: Internal server error

  '/projects/{id}/assign/participants':
    post:
      summary: Assign participants to project
      operationId: assignProjectParticipants
      parameters:
        - name: id
          in: path
          description: ID of the project to assign participants to
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                employeeIds:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Project is updated
        '400':
          description: Bad request
        '404':
          description: Not Found
        '500':
          description: Internal server error